name: Run Test Suite

on:
  push:
    branches: [ "root" ]
  pull_request:
    branches: [ "root" ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: 6.1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v